### ISSUE TITLE
ncdns v0.0.10 - failed to query namecoin

### ISSUE THREAD

**Issue by redblade7** [namecoin/ncbtcjson#4]
With the latest version of ncdns (v0.0.10) attempting to look up a .bit domain gives a SERVFAIL. ncdns, when not forked, shows this message:

> [ERROR] ncdns.backend: failed to query namecoin: -1: name_show "name"
> 
> (the help entry for name_show follows)

No problems with ncdns v0.0.9.

**Comment by JeremyRand** [comment]
I might have a trivially easy fix, actually.  Stand by.
